title : Shabang.DEV: Learn how to code! 
description: 'A website for teaching you how to code!'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
plugins: [jekyll-gist]
permalink: /:title.html
